ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ example.com.ApplicationKt.module ]
    }
}
jwt {
    #recipient of the token.
    audience = "audience"
    #The entity that issues the token.
    issuer = "http://198.199.122.146"
    #optional parameter that provides additional context or scope
    realm = "my-realm"
    #A secret key used for token signing and verification.
    #Apparently should never hard code - how could it be found, though?
    secret = ${SECRET}
}
database {
    val driverClassName = "com.mysql.cj.jdbc.Driver"
    jdbcURL = "jdbc:mysql://198.199.122.146:3306/NOTEAPPLICATION"
    user = "root"
    password = ""
}