ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ example.com.ApplicationKt.module ]
    }
}
jwt {
    audience = "note-app-api"
    #The entity that issues the tokens
    issuer = "http://198.199.122.146"
    realm = "note-app-auth"
    secret = ${SECRET}
}
database {
    val driverClassName = "com.mysql.cj.jdbc.Driver"
    jdbcURL = "jdbc:mysql://198.199.122.146:3306/NOTEAPPLICATION"
    user = "root"
    password = ""
}